title: "DM1 : Statistiques de base"

subtitle: "M2MSR 2023-2024"

author:
  name: "**Groupe 11** - Julien ELICES-DIEZ"
  email: "ju.diez@protonmail.com"

filters:
  - add-code-files

format:
  hebstr-template-html:
    code-tools:
      source: https://codeberg.org/hebstr/m2_dm1/src/branch/main/
  hebstr-template-typst: default
