[project]
name = "m2_dm1"
r_version = "4.5"

repositories = [
    { alias = "CRAN", url = "https://packagemanager.posit.co/cran/latest" },
]

dependencies = [
    { name = "hebstr", git = "https://github.com/hebstr/hebstr", branch = "main" },
    "tidyverse",
    "corrr",
    "patchwork",
    "gtsummary",
    "labelled",
    "here",
    "devtools",
    "pak",
    "rsvg",
    "car",
    "parameters",
]
